update scripts
- sorting applies to all systems structured around mame roms.
- prescan applies to all relevant systems.
- mamexml-generate generalized and called from multiple scripts.
- mameinfo can now handle a huge collection of roms at once.
- short flags for raconfig
- geneneral cleanup, code style updates.

diff --git a/scripts/mame-prescan b/scripts/mame-prescan
--- a/scripts/mame-prescan
+++ b/scripts/mame-prescan
@@ -1,15 +1,86 @@
 #!/usr/bin/env zsh
 
-PATH=$( dirname `realpath $0` ):$PATH
-scandir=~/Games/Emulation/Arcade
+PATH=${0:A:h}:$PATH
 
-printf '\e[0;30mUpdating %s file for MAME.lpl...\e[0m\n' $scandir:t.xml
-mamexml-generate $scandir
+p.header() { printf '\e[1;30m%s\e[0m\n' $@ }
+p.notice() { printf '\e[0;30m%s\e[0m\n' $@ }
+p.error()  { printf '\e[0;30m%s\e[0m\n' $@ >&2 }
 
-printf '\e[0;30m%s\e[0m\n' 'Sorting ROMs...'
-mamerom-sort $scandir
-printf '\e[0;33m%s\e[0m\n' 'Sorting complete. Ready to rescan MAME.lpl'
+typeset -A systems=(
+  atomiswave  Atomiswave.lpl
+  mame        MAME.lpl
+  naomi       Sega\ -\ Naomi.lpl
+  naomi2      Sega\ -\ Naomi\ 2.lpl
+)
+for system in ${@:-${(k)systems}}
+do
+  playlist=${systems[$system]}
+  if [[ ! -n $playlist ]]
+  then
+    p.error "$system not recognized." "available systems: [${(kj/|/)systems}]"
+    exit 1
+  fi
+  playlist_path=$( raconfig -g playlist_directory )/$playlist
 
-printf '\e[0;30m%s\e[0m\n' 'Processing MAME config overrides...'
-mamecfg-overrides $scandir
-printf '\e[0;30m%s\e[0m\n' 'Done.'
+  # Get and validate required paths from playlist.
+  for key in scan_content_dir scan_dat_file_path
+  do
+    value=${$( jq -r .$key $playlist_path ):-null}
+    if [[ $value == null ]]
+    then
+      p.error "$playlist -> $key: has no value."
+      exit 1
+    elif [[ ! -s ${value:h} ]]
+    then
+      p.error "$playlist -> $key: points to a non-existing directory:"
+      p.error "'$value'"
+      exit 1
+    fi
+    case $key in
+      scan_content_dir)
+        scandir=${value%\/.sorted}
+        update_scan_content_dir=$(( $#value - $#scandir == 0 ))
+        ;;
+      scan_dat_file_path)
+        scandat=$value
+        ;;
+    esac
+  done
+
+  p.header "Updating ${scandat:t} -> $playlist"
+  if ! mamexml-generate $scandir $scandat
+  then
+    p.error "Failed to generate xml for rom path:"
+    p.error "'$scandir'"
+    exit 1
+  fi
+
+  p.header "Sorting '$scandir'"
+  if mamerom-sort $scandir
+  then
+    if (( update_scan_content_dir ))
+    then
+      temp=`mktemp -u`
+      if jq '.scan_content_dir += "/.sorted"' $playlist_path > $temp
+      then
+        mv -f $temp $playlist_path
+        p.notice "Updated $playlist -> scan_content_dir:"
+        p.notice "'$scandir/.sorted'"
+      else
+        p.error "Failed to update $playlist -> scan_content_dir."
+      fi
+    fi
+  else
+    p.error "Sorting failed."
+    exit 1
+  fi
+
+  if [[ $system == mame ]]
+  then
+    p.header "Processing MAME config overrides…"
+    if mamecfg-overrides $scandir
+    then p.notice Done.
+    else exit 1
+    fi
+  fi
+done
diff --git a/scripts/update-cores b/scripts/update-cores
--- a/scripts/update-cores
+++ b/scripts/update-cores
@@ -3,8 +3,7 @@
 PATH=$( dirname `realpath $0` ):$PATH
 
 if [[ $( raconfig --get config_save_minimal ) == true ]]
-then
-  p.error "Incompatible with 'config_save_minimal'."
+then p.error "Incompatible with 'config_save_minimal'."
   return 1
 fi
 
@@ -13,13 +12,11 @@ do
   name=${${dylib:t}%_libretro.dylib}
   info=$( raconfig --get libretro_info_path )/$dylib:t:r.info
   if [[ -f $info ]]
-  then
-    name=${$( raconfig --get corename $info ):-$name}
+  then name=${$( raconfig --get corename $info ):-$name}
   fi
 
   if [[ -f $dylib:r.lck ]]
-  then
-    echo "$name is locked."
+  then echo "$name is locked."
     continue
   fi
 
@@ -58,16 +55,13 @@ do
 
   echo "downloading $name core..."
   if ! curl -#Lo $tmpdir/$dylib:t.zip https://buildbot.libretro.com/nightly/apple/osx/$arch/latest/$dylib:t.zip
-  then
-    echo "download failed." >&2
+  then echo "download failed." >&2
     continue
   fi
 
   if unzip -q $tmpdir/$dylib:t.zip -d $tmpdir
-  then
-    mv -f $tmpdir/$dylib:t $dylib
-  else
-    echo "failed to extract core." >&2
+  then mv -f $tmpdir/$dylib:t $dylib
+  else echo "failed to extract core." >&2
     continue
   fi
 
